Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"
    config.vm.box_check_update = true
    config.vm.network "forwarded_port", guest: 9092, host: 9092, auto_correct: true
    config.vm.network "forwarded_port", guest: 6667, host: 6667, auto_correct: true
    config.vm.network "forwarded_port", guest: 22, host: 22102, auto_correct: true, id: 'ssh'
    config.vm.network "private_network", ip: "192.168.56.102"
    config.vm.hostname = "kafka-host.local"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.boot_timeout = 600

    config.vm.provider "virtualbox" do |vb|
        vb.name = "kafka-host.local"
        vb.gui = true
        vb.memory = "2048"
        vb.check_guest_additions = true
        vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end

end