Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"
    config.vm.box_check_update = true
    config.vm.network "forwarded_port", guest: 3306, host: 3306, auto_correct: true
    config.vm.network "forwarded_port", guest: 22, host: 22100, auto_correct: true, id: 'ssh'
    config.vm.network "private_network", ip: ENV['MYSQL_PRIVATE_IP']
    config.vm.network "public_network", ip: ENV['MYSQL_PUBLIC_IP'], bridge: ENV['BRIDGE_NETWORK_IFACE_NAME']
    config.vm.hostname = "mysql-host.local"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.boot_timeout = 600

    config.vm.provider "virtualbox" do |vb|
        vb.name = "mysql-host.local"
        vb.gui = true
        vb.memory = "2048"
        vb.check_guest_additions = true
        vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end

end